### ISSUE TITLE
Clarification on sign up flow

### ISSUE THREAD

**Issue by bcessa** [aidtechnology/affinity-sdk#1]
The objective for this integration step is to abstract away the process of registering a new DID and associated wallet for the user. 

**CA:** Caregiver Application
**SDK:** Affinity SDK

- CA assign an internal identifier (i.e., username) for the user; for example an insurance account number, citizen ID, etc.
- CA generates and securely store the associated password for the user.
- CA uses the SDK to generate a new DID and associated wallet for the user by providing the username and password. **It should not be required for the user to receive and provide any confirmation code.**
- The data returned by the SDK will be securely stored by the CA. The information returned should contain everything required to perform **authentication and requesting credentials**.

Currently we are trying to accomplish this using the `fromLoginAndPassword` method in the Core SDK.

```js
let cnm = await CommonNetworkMember.fromLoginAndPassword(this.state.username, this.state.password);
```

But an error is produced.

![Screen Shot 2020-06-25 at 9 22 34 AM](https://user-images.githubusercontent.com/259803/85733108-ebdc8180-b6c9-11ea-8693-65ae85aa184d.png)

@fungust

**Comment by fungust** [comment]
Hi @bcessa , thank you for reporting this.

I have communicated and discussed the issue with our network team. We have made some improvements to resolve the issue.

Please find the directions to resolve this issue below:

1.  Call `const token = await CommonNetworkMember.signUp(username, password);` for user registration (as is being done now in your application)
2.  Call `const wallet = await CommonNetworkMember.confirmSignUp(token);` to confirm the user (no confirmation code argument required, just the token from step 1 above.
3.  To login, call `const wallet = await CommonNetworkMember.fromLoginAndPassword(username, password);`

This should resolve the error you are encountering above. I would be grateful if you could check that this revised flow is suitable for Aid:tech's requirements. Would be more than willing to jump on a call later this evening as necessary to discuss this! Thank you!

**Comment by benediktolek** [comment]
Hey @bcessa,

are you able to fix the problem? Is there anything we can help with to close this issue?

Thanks

**Comment by bcessa** [comment]
Thanks @fungust working great now 👍
